### ISSUE TITLE
Ansible fact or create new fact for Pi board revision?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [geerlingguy/ansible-role-raspberry-pi#7]
Ansible fact or create new fact for Pi board revision?  Looking for a way to run specific ansible tasks based on the Pi device being 32 or 64 bit.  For example setting config.txt arm_64bit=0 or 1?

**Comment by Jibun-no-Kage** [comment]
So because no one responds it gets closed?

**Comment by geerlingguy** [comment]
Yes, unfortunately. See: https://www.jeffgeerling.com/blog/2020/enabling-stale-issue-bot-on-my-github-repositories
